// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: j-system.piqi.proto

public final class JSystemPiqi {
  private JSystemPiqi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface grant_coins_requestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string userid = 1;
    boolean hasUserid();
    String getUserid();
    
    // required uint32 coins = 2;
    boolean hasCoins();
    int getCoins();
  }
  public static final class grant_coins_request extends
      com.google.protobuf.GeneratedMessage
      implements grant_coins_requestOrBuilder {
    // Use grant_coins_request.newBuilder() to construct.
    private grant_coins_request(Builder builder) {
      super(builder);
    }
    private grant_coins_request(boolean noInit) {}
    
    private static final grant_coins_request defaultInstance;
    public static grant_coins_request getDefaultInstance() {
      return defaultInstance;
    }
    
    public grant_coins_request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JSystemPiqi.internal_static_grant_coins_request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JSystemPiqi.internal_static_grant_coins_request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string userid = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userid_;
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserid() {
      java.lang.Object ref = userid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUseridBytes() {
      java.lang.Object ref = userid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required uint32 coins = 2;
    public static final int COINS_FIELD_NUMBER = 2;
    private int coins_;
    public boolean hasCoins() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCoins() {
      return coins_;
    }
    
    private void initFields() {
      userid_ = "";
      coins_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCoins()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUseridBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, coins_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUseridBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, coins_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static JSystemPiqi.grant_coins_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static JSystemPiqi.grant_coins_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.grant_coins_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static JSystemPiqi.grant_coins_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.grant_coins_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static JSystemPiqi.grant_coins_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.grant_coins_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static JSystemPiqi.grant_coins_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static JSystemPiqi.grant_coins_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static JSystemPiqi.grant_coins_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(JSystemPiqi.grant_coins_request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements JSystemPiqi.grant_coins_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JSystemPiqi.internal_static_grant_coins_request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JSystemPiqi.internal_static_grant_coins_request_fieldAccessorTable;
      }
      
      // Construct using JSystemPiqi.grant_coins_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        coins_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JSystemPiqi.grant_coins_request.getDescriptor();
      }
      
      public JSystemPiqi.grant_coins_request getDefaultInstanceForType() {
        return JSystemPiqi.grant_coins_request.getDefaultInstance();
      }
      
      public JSystemPiqi.grant_coins_request build() {
        JSystemPiqi.grant_coins_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private JSystemPiqi.grant_coins_request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        JSystemPiqi.grant_coins_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public JSystemPiqi.grant_coins_request buildPartial() {
        JSystemPiqi.grant_coins_request result = new JSystemPiqi.grant_coins_request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.coins_ = coins_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JSystemPiqi.grant_coins_request) {
          return mergeFrom((JSystemPiqi.grant_coins_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(JSystemPiqi.grant_coins_request other) {
        if (other == JSystemPiqi.grant_coins_request.getDefaultInstance()) return this;
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasCoins()) {
          setCoins(other.getCoins());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserid()) {
          
          return false;
        }
        if (!hasCoins()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userid_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              coins_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string userid = 1;
      private java.lang.Object userid_ = "";
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserid() {
        java.lang.Object ref = userid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userid_ = getDefaultInstance().getUserid();
        onChanged();
        return this;
      }
      void setUserid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
      }
      
      // required uint32 coins = 2;
      private int coins_ ;
      public boolean hasCoins() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCoins() {
        return coins_;
      }
      public Builder setCoins(int value) {
        bitField0_ |= 0x00000002;
        coins_ = value;
        onChanged();
        return this;
      }
      public Builder clearCoins() {
        bitField0_ = (bitField0_ & ~0x00000002);
        coins_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:grant_coins_request)
    }
    
    static {
      defaultInstance = new grant_coins_request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:grant_coins_request)
  }
  
  public interface buy_item_requestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string userid = 1;
    boolean hasUserid();
    String getUserid();
    
    // required uint32 shop_item_id = 2;
    boolean hasShopItemId();
    int getShopItemId();
    
    // required uint32 amount = 3;
    boolean hasAmount();
    int getAmount();
  }
  public static final class buy_item_request extends
      com.google.protobuf.GeneratedMessage
      implements buy_item_requestOrBuilder {
    // Use buy_item_request.newBuilder() to construct.
    private buy_item_request(Builder builder) {
      super(builder);
    }
    private buy_item_request(boolean noInit) {}
    
    private static final buy_item_request defaultInstance;
    public static buy_item_request getDefaultInstance() {
      return defaultInstance;
    }
    
    public buy_item_request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JSystemPiqi.internal_static_buy_item_request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JSystemPiqi.internal_static_buy_item_request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string userid = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userid_;
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserid() {
      java.lang.Object ref = userid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUseridBytes() {
      java.lang.Object ref = userid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required uint32 shop_item_id = 2;
    public static final int SHOP_ITEM_ID_FIELD_NUMBER = 2;
    private int shopItemId_;
    public boolean hasShopItemId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getShopItemId() {
      return shopItemId_;
    }
    
    // required uint32 amount = 3;
    public static final int AMOUNT_FIELD_NUMBER = 3;
    private int amount_;
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getAmount() {
      return amount_;
    }
    
    private void initFields() {
      userid_ = "";
      shopItemId_ = 0;
      amount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasShopItemId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUseridBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, shopItemId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, amount_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUseridBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, shopItemId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, amount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static JSystemPiqi.buy_item_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static JSystemPiqi.buy_item_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.buy_item_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static JSystemPiqi.buy_item_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.buy_item_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static JSystemPiqi.buy_item_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.buy_item_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static JSystemPiqi.buy_item_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static JSystemPiqi.buy_item_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static JSystemPiqi.buy_item_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(JSystemPiqi.buy_item_request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements JSystemPiqi.buy_item_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JSystemPiqi.internal_static_buy_item_request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JSystemPiqi.internal_static_buy_item_request_fieldAccessorTable;
      }
      
      // Construct using JSystemPiqi.buy_item_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        shopItemId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        amount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JSystemPiqi.buy_item_request.getDescriptor();
      }
      
      public JSystemPiqi.buy_item_request getDefaultInstanceForType() {
        return JSystemPiqi.buy_item_request.getDefaultInstance();
      }
      
      public JSystemPiqi.buy_item_request build() {
        JSystemPiqi.buy_item_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private JSystemPiqi.buy_item_request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        JSystemPiqi.buy_item_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public JSystemPiqi.buy_item_request buildPartial() {
        JSystemPiqi.buy_item_request result = new JSystemPiqi.buy_item_request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.shopItemId_ = shopItemId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.amount_ = amount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JSystemPiqi.buy_item_request) {
          return mergeFrom((JSystemPiqi.buy_item_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(JSystemPiqi.buy_item_request other) {
        if (other == JSystemPiqi.buy_item_request.getDefaultInstance()) return this;
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasShopItemId()) {
          setShopItemId(other.getShopItemId());
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserid()) {
          
          return false;
        }
        if (!hasShopItemId()) {
          
          return false;
        }
        if (!hasAmount()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userid_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              shopItemId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              amount_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string userid = 1;
      private java.lang.Object userid_ = "";
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserid() {
        java.lang.Object ref = userid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userid_ = getDefaultInstance().getUserid();
        onChanged();
        return this;
      }
      void setUserid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
      }
      
      // required uint32 shop_item_id = 2;
      private int shopItemId_ ;
      public boolean hasShopItemId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getShopItemId() {
        return shopItemId_;
      }
      public Builder setShopItemId(int value) {
        bitField0_ |= 0x00000002;
        shopItemId_ = value;
        onChanged();
        return this;
      }
      public Builder clearShopItemId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        shopItemId_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 amount = 3;
      private int amount_ ;
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getAmount() {
        return amount_;
      }
      public Builder setAmount(int value) {
        bitField0_ |= 0x00000004;
        amount_ = value;
        onChanged();
        return this;
      }
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        amount_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:buy_item_request)
    }
    
    static {
      defaultInstance = new buy_item_request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:buy_item_request)
  }
  
  public interface system_requestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .buy_item_request buy_item = 1;
    boolean hasBuyItem();
    JSystemPiqi.buy_item_request getBuyItem();
    JSystemPiqi.buy_item_requestOrBuilder getBuyItemOrBuilder();
    
    // optional .grant_coins_request grant_coins = 2;
    boolean hasGrantCoins();
    JSystemPiqi.grant_coins_request getGrantCoins();
    JSystemPiqi.grant_coins_requestOrBuilder getGrantCoinsOrBuilder();
  }
  public static final class system_request extends
      com.google.protobuf.GeneratedMessage
      implements system_requestOrBuilder {
    // Use system_request.newBuilder() to construct.
    private system_request(Builder builder) {
      super(builder);
    }
    private system_request(boolean noInit) {}
    
    private static final system_request defaultInstance;
    public static system_request getDefaultInstance() {
      return defaultInstance;
    }
    
    public system_request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JSystemPiqi.internal_static_system_request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JSystemPiqi.internal_static_system_request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .buy_item_request buy_item = 1;
    public static final int BUY_ITEM_FIELD_NUMBER = 1;
    private JSystemPiqi.buy_item_request buyItem_;
    public boolean hasBuyItem() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public JSystemPiqi.buy_item_request getBuyItem() {
      return buyItem_;
    }
    public JSystemPiqi.buy_item_requestOrBuilder getBuyItemOrBuilder() {
      return buyItem_;
    }
    
    // optional .grant_coins_request grant_coins = 2;
    public static final int GRANT_COINS_FIELD_NUMBER = 2;
    private JSystemPiqi.grant_coins_request grantCoins_;
    public boolean hasGrantCoins() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public JSystemPiqi.grant_coins_request getGrantCoins() {
      return grantCoins_;
    }
    public JSystemPiqi.grant_coins_requestOrBuilder getGrantCoinsOrBuilder() {
      return grantCoins_;
    }
    
    private void initFields() {
      buyItem_ = JSystemPiqi.buy_item_request.getDefaultInstance();
      grantCoins_ = JSystemPiqi.grant_coins_request.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasBuyItem()) {
        if (!getBuyItem().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGrantCoins()) {
        if (!getGrantCoins().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, buyItem_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, grantCoins_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, buyItem_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, grantCoins_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static JSystemPiqi.system_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static JSystemPiqi.system_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.system_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static JSystemPiqi.system_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.system_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static JSystemPiqi.system_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.system_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static JSystemPiqi.system_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static JSystemPiqi.system_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static JSystemPiqi.system_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(JSystemPiqi.system_request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements JSystemPiqi.system_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JSystemPiqi.internal_static_system_request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JSystemPiqi.internal_static_system_request_fieldAccessorTable;
      }
      
      // Construct using JSystemPiqi.system_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBuyItemFieldBuilder();
          getGrantCoinsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (buyItemBuilder_ == null) {
          buyItem_ = JSystemPiqi.buy_item_request.getDefaultInstance();
        } else {
          buyItemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (grantCoinsBuilder_ == null) {
          grantCoins_ = JSystemPiqi.grant_coins_request.getDefaultInstance();
        } else {
          grantCoinsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JSystemPiqi.system_request.getDescriptor();
      }
      
      public JSystemPiqi.system_request getDefaultInstanceForType() {
        return JSystemPiqi.system_request.getDefaultInstance();
      }
      
      public JSystemPiqi.system_request build() {
        JSystemPiqi.system_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private JSystemPiqi.system_request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        JSystemPiqi.system_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public JSystemPiqi.system_request buildPartial() {
        JSystemPiqi.system_request result = new JSystemPiqi.system_request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (buyItemBuilder_ == null) {
          result.buyItem_ = buyItem_;
        } else {
          result.buyItem_ = buyItemBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (grantCoinsBuilder_ == null) {
          result.grantCoins_ = grantCoins_;
        } else {
          result.grantCoins_ = grantCoinsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JSystemPiqi.system_request) {
          return mergeFrom((JSystemPiqi.system_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(JSystemPiqi.system_request other) {
        if (other == JSystemPiqi.system_request.getDefaultInstance()) return this;
        if (other.hasBuyItem()) {
          mergeBuyItem(other.getBuyItem());
        }
        if (other.hasGrantCoins()) {
          mergeGrantCoins(other.getGrantCoins());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasBuyItem()) {
          if (!getBuyItem().isInitialized()) {
            
            return false;
          }
        }
        if (hasGrantCoins()) {
          if (!getGrantCoins().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              JSystemPiqi.buy_item_request.Builder subBuilder = JSystemPiqi.buy_item_request.newBuilder();
              if (hasBuyItem()) {
                subBuilder.mergeFrom(getBuyItem());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBuyItem(subBuilder.buildPartial());
              break;
            }
            case 18: {
              JSystemPiqi.grant_coins_request.Builder subBuilder = JSystemPiqi.grant_coins_request.newBuilder();
              if (hasGrantCoins()) {
                subBuilder.mergeFrom(getGrantCoins());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGrantCoins(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .buy_item_request buy_item = 1;
      private JSystemPiqi.buy_item_request buyItem_ = JSystemPiqi.buy_item_request.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          JSystemPiqi.buy_item_request, JSystemPiqi.buy_item_request.Builder, JSystemPiqi.buy_item_requestOrBuilder> buyItemBuilder_;
      public boolean hasBuyItem() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public JSystemPiqi.buy_item_request getBuyItem() {
        if (buyItemBuilder_ == null) {
          return buyItem_;
        } else {
          return buyItemBuilder_.getMessage();
        }
      }
      public Builder setBuyItem(JSystemPiqi.buy_item_request value) {
        if (buyItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          buyItem_ = value;
          onChanged();
        } else {
          buyItemBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setBuyItem(
          JSystemPiqi.buy_item_request.Builder builderForValue) {
        if (buyItemBuilder_ == null) {
          buyItem_ = builderForValue.build();
          onChanged();
        } else {
          buyItemBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeBuyItem(JSystemPiqi.buy_item_request value) {
        if (buyItemBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              buyItem_ != JSystemPiqi.buy_item_request.getDefaultInstance()) {
            buyItem_ =
              JSystemPiqi.buy_item_request.newBuilder(buyItem_).mergeFrom(value).buildPartial();
          } else {
            buyItem_ = value;
          }
          onChanged();
        } else {
          buyItemBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearBuyItem() {
        if (buyItemBuilder_ == null) {
          buyItem_ = JSystemPiqi.buy_item_request.getDefaultInstance();
          onChanged();
        } else {
          buyItemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public JSystemPiqi.buy_item_request.Builder getBuyItemBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBuyItemFieldBuilder().getBuilder();
      }
      public JSystemPiqi.buy_item_requestOrBuilder getBuyItemOrBuilder() {
        if (buyItemBuilder_ != null) {
          return buyItemBuilder_.getMessageOrBuilder();
        } else {
          return buyItem_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          JSystemPiqi.buy_item_request, JSystemPiqi.buy_item_request.Builder, JSystemPiqi.buy_item_requestOrBuilder> 
          getBuyItemFieldBuilder() {
        if (buyItemBuilder_ == null) {
          buyItemBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              JSystemPiqi.buy_item_request, JSystemPiqi.buy_item_request.Builder, JSystemPiqi.buy_item_requestOrBuilder>(
                  buyItem_,
                  getParentForChildren(),
                  isClean());
          buyItem_ = null;
        }
        return buyItemBuilder_;
      }
      
      // optional .grant_coins_request grant_coins = 2;
      private JSystemPiqi.grant_coins_request grantCoins_ = JSystemPiqi.grant_coins_request.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          JSystemPiqi.grant_coins_request, JSystemPiqi.grant_coins_request.Builder, JSystemPiqi.grant_coins_requestOrBuilder> grantCoinsBuilder_;
      public boolean hasGrantCoins() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public JSystemPiqi.grant_coins_request getGrantCoins() {
        if (grantCoinsBuilder_ == null) {
          return grantCoins_;
        } else {
          return grantCoinsBuilder_.getMessage();
        }
      }
      public Builder setGrantCoins(JSystemPiqi.grant_coins_request value) {
        if (grantCoinsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          grantCoins_ = value;
          onChanged();
        } else {
          grantCoinsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setGrantCoins(
          JSystemPiqi.grant_coins_request.Builder builderForValue) {
        if (grantCoinsBuilder_ == null) {
          grantCoins_ = builderForValue.build();
          onChanged();
        } else {
          grantCoinsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeGrantCoins(JSystemPiqi.grant_coins_request value) {
        if (grantCoinsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              grantCoins_ != JSystemPiqi.grant_coins_request.getDefaultInstance()) {
            grantCoins_ =
              JSystemPiqi.grant_coins_request.newBuilder(grantCoins_).mergeFrom(value).buildPartial();
          } else {
            grantCoins_ = value;
          }
          onChanged();
        } else {
          grantCoinsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearGrantCoins() {
        if (grantCoinsBuilder_ == null) {
          grantCoins_ = JSystemPiqi.grant_coins_request.getDefaultInstance();
          onChanged();
        } else {
          grantCoinsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public JSystemPiqi.grant_coins_request.Builder getGrantCoinsBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getGrantCoinsFieldBuilder().getBuilder();
      }
      public JSystemPiqi.grant_coins_requestOrBuilder getGrantCoinsOrBuilder() {
        if (grantCoinsBuilder_ != null) {
          return grantCoinsBuilder_.getMessageOrBuilder();
        } else {
          return grantCoins_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          JSystemPiqi.grant_coins_request, JSystemPiqi.grant_coins_request.Builder, JSystemPiqi.grant_coins_requestOrBuilder> 
          getGrantCoinsFieldBuilder() {
        if (grantCoinsBuilder_ == null) {
          grantCoinsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              JSystemPiqi.grant_coins_request, JSystemPiqi.grant_coins_request.Builder, JSystemPiqi.grant_coins_requestOrBuilder>(
                  grantCoins_,
                  getParentForChildren(),
                  isClean());
          grantCoins_ = null;
        }
        return grantCoinsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:system_request)
    }
    
    static {
      defaultInstance = new system_request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:system_request)
  }
  
  public interface system_errorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 code = 1;
    boolean hasCode();
    int getCode();
    
    // optional string description = 2;
    boolean hasDescription();
    String getDescription();
  }
  public static final class system_error extends
      com.google.protobuf.GeneratedMessage
      implements system_errorOrBuilder {
    // Use system_error.newBuilder() to construct.
    private system_error(Builder builder) {
      super(builder);
    }
    private system_error(boolean noInit) {}
    
    private static final system_error defaultInstance;
    public static system_error getDefaultInstance() {
      return defaultInstance;
    }
    
    public system_error getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JSystemPiqi.internal_static_system_error_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JSystemPiqi.internal_static_system_error_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCode() {
      return code_;
    }
    
    // optional string description = 2;
    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      code_ = 0;
      description_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDescriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDescriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static JSystemPiqi.system_error parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static JSystemPiqi.system_error parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.system_error parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static JSystemPiqi.system_error parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.system_error parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static JSystemPiqi.system_error parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.system_error parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static JSystemPiqi.system_error parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static JSystemPiqi.system_error parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static JSystemPiqi.system_error parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(JSystemPiqi.system_error prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements JSystemPiqi.system_errorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JSystemPiqi.internal_static_system_error_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JSystemPiqi.internal_static_system_error_fieldAccessorTable;
      }
      
      // Construct using JSystemPiqi.system_error.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JSystemPiqi.system_error.getDescriptor();
      }
      
      public JSystemPiqi.system_error getDefaultInstanceForType() {
        return JSystemPiqi.system_error.getDefaultInstance();
      }
      
      public JSystemPiqi.system_error build() {
        JSystemPiqi.system_error result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private JSystemPiqi.system_error buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        JSystemPiqi.system_error result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public JSystemPiqi.system_error buildPartial() {
        JSystemPiqi.system_error result = new JSystemPiqi.system_error(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JSystemPiqi.system_error) {
          return mergeFrom((JSystemPiqi.system_error)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(JSystemPiqi.system_error other) {
        if (other == JSystemPiqi.system_error.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              description_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 code = 1;
      private int code_ ;
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCode() {
        return code_;
      }
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }
      
      // optional string description = 2;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:system_error)
    }
    
    static {
      defaultInstance = new system_error(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:system_error)
  }
  
  public interface system_responseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bool ok = 1;
    boolean hasOk();
    boolean getOk();
    
    // optional .system_error error = 2;
    boolean hasError();
    JSystemPiqi.system_error getError();
    JSystemPiqi.system_errorOrBuilder getErrorOrBuilder();
  }
  public static final class system_response extends
      com.google.protobuf.GeneratedMessage
      implements system_responseOrBuilder {
    // Use system_response.newBuilder() to construct.
    private system_response(Builder builder) {
      super(builder);
    }
    private system_response(boolean noInit) {}
    
    private static final system_response defaultInstance;
    public static system_response getDefaultInstance() {
      return defaultInstance;
    }
    
    public system_response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JSystemPiqi.internal_static_system_response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JSystemPiqi.internal_static_system_response_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bool ok = 1;
    public static final int OK_FIELD_NUMBER = 1;
    private boolean ok_;
    public boolean hasOk() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getOk() {
      return ok_;
    }
    
    // optional .system_error error = 2;
    public static final int ERROR_FIELD_NUMBER = 2;
    private JSystemPiqi.system_error error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public JSystemPiqi.system_error getError() {
      return error_;
    }
    public JSystemPiqi.system_errorOrBuilder getErrorOrBuilder() {
      return error_;
    }
    
    private void initFields() {
      ok_ = false;
      error_ = JSystemPiqi.system_error.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, ok_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, error_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ok_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, error_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static JSystemPiqi.system_response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static JSystemPiqi.system_response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.system_response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static JSystemPiqi.system_response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.system_response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static JSystemPiqi.system_response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static JSystemPiqi.system_response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static JSystemPiqi.system_response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static JSystemPiqi.system_response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static JSystemPiqi.system_response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(JSystemPiqi.system_response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements JSystemPiqi.system_responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JSystemPiqi.internal_static_system_response_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JSystemPiqi.internal_static_system_response_fieldAccessorTable;
      }
      
      // Construct using JSystemPiqi.system_response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getErrorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ok_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (errorBuilder_ == null) {
          error_ = JSystemPiqi.system_error.getDefaultInstance();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JSystemPiqi.system_response.getDescriptor();
      }
      
      public JSystemPiqi.system_response getDefaultInstanceForType() {
        return JSystemPiqi.system_response.getDefaultInstance();
      }
      
      public JSystemPiqi.system_response build() {
        JSystemPiqi.system_response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private JSystemPiqi.system_response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        JSystemPiqi.system_response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public JSystemPiqi.system_response buildPartial() {
        JSystemPiqi.system_response result = new JSystemPiqi.system_response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ok_ = ok_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JSystemPiqi.system_response) {
          return mergeFrom((JSystemPiqi.system_response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(JSystemPiqi.system_response other) {
        if (other == JSystemPiqi.system_response.getDefaultInstance()) return this;
        if (other.hasOk()) {
          setOk(other.getOk());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ok_ = input.readBool();
              break;
            }
            case 18: {
              JSystemPiqi.system_error.Builder subBuilder = JSystemPiqi.system_error.newBuilder();
              if (hasError()) {
                subBuilder.mergeFrom(getError());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setError(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bool ok = 1;
      private boolean ok_ ;
      public boolean hasOk() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getOk() {
        return ok_;
      }
      public Builder setOk(boolean value) {
        bitField0_ |= 0x00000001;
        ok_ = value;
        onChanged();
        return this;
      }
      public Builder clearOk() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ok_ = false;
        onChanged();
        return this;
      }
      
      // optional .system_error error = 2;
      private JSystemPiqi.system_error error_ = JSystemPiqi.system_error.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          JSystemPiqi.system_error, JSystemPiqi.system_error.Builder, JSystemPiqi.system_errorOrBuilder> errorBuilder_;
      public boolean hasError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public JSystemPiqi.system_error getError() {
        if (errorBuilder_ == null) {
          return error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      public Builder setError(JSystemPiqi.system_error value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setError(
          JSystemPiqi.system_error.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeError(JSystemPiqi.system_error value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              error_ != JSystemPiqi.system_error.getDefaultInstance()) {
            error_ =
              JSystemPiqi.system_error.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = JSystemPiqi.system_error.getDefaultInstance();
          onChanged();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public JSystemPiqi.system_error.Builder getErrorBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      public JSystemPiqi.system_errorOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          JSystemPiqi.system_error, JSystemPiqi.system_error.Builder, JSystemPiqi.system_errorOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              JSystemPiqi.system_error, JSystemPiqi.system_error.Builder, JSystemPiqi.system_errorOrBuilder>(
                  error_,
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:system_response)
    }
    
    static {
      defaultInstance = new system_response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:system_response)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_grant_coins_request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grant_coins_request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_buy_item_request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_buy_item_request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_system_request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_system_request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_system_error_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_system_error_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_system_response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_system_response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023j-system.piqi.proto\"4\n\023grant_coins_req" +
      "uest\022\016\n\006userid\030\001 \002(\t\022\r\n\005coins\030\002 \002(\r\"H\n\020b" +
      "uy_item_request\022\016\n\006userid\030\001 \002(\t\022\024\n\014shop_" +
      "item_id\030\002 \002(\r\022\016\n\006amount\030\003 \002(\r\"`\n\016system_" +
      "request\022#\n\010buy_item\030\001 \001(\0132\021.buy_item_req" +
      "uest\022)\n\013grant_coins\030\002 \001(\0132\024.grant_coins_" +
      "request\"1\n\014system_error\022\014\n\004code\030\001 \001(\r\022\023\n" +
      "\013description\030\002 \001(\t\";\n\017system_response\022\n\n" +
      "\002ok\030\001 \001(\010\022\034\n\005error\030\002 \001(\0132\r.system_error"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_grant_coins_request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_grant_coins_request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_grant_coins_request_descriptor,
              new java.lang.String[] { "Userid", "Coins", },
              JSystemPiqi.grant_coins_request.class,
              JSystemPiqi.grant_coins_request.Builder.class);
          internal_static_buy_item_request_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_buy_item_request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_buy_item_request_descriptor,
              new java.lang.String[] { "Userid", "ShopItemId", "Amount", },
              JSystemPiqi.buy_item_request.class,
              JSystemPiqi.buy_item_request.Builder.class);
          internal_static_system_request_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_system_request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_system_request_descriptor,
              new java.lang.String[] { "BuyItem", "GrantCoins", },
              JSystemPiqi.system_request.class,
              JSystemPiqi.system_request.Builder.class);
          internal_static_system_error_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_system_error_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_system_error_descriptor,
              new java.lang.String[] { "Code", "Description", },
              JSystemPiqi.system_error.class,
              JSystemPiqi.system_error.Builder.class);
          internal_static_system_response_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_system_response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_system_response_descriptor,
              new java.lang.String[] { "Ok", "Error", },
              JSystemPiqi.system_response.class,
              JSystemPiqi.system_response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
